[files]
extend-exclude = [
    ".git/",
    "docs/_static/css/fontawesome.min.css",
    "docs/README_*",
    "src/libs/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bser[^a-z]",
    "\\bfle[^a-z]",
    '"Lorem ipsum .*"',
    "Nam consectetur",
    "U\\+[0-9A-F]{4}",
    '\{ "[a-z]+", "[^ -~]+" \},',
    "`[0-9a-f]{7} <https://\\S+>`__",
    "Rename lv_chart_clear_serie",
    "rename LV_ROLLER_MODE_INIFINITE",
    "CARD_INFO_SET\\(&img_multilang_avatar_.*\\)",
    "ACI\\)",
]

[default.extend-words]
# https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6loca.html
"loca" = "loca"
