name: Build Micropython with LVGL submodule

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev parallel
    - name: Clone lv_micropython
      run: |
        git clone https://github.com/lvgl/lv_micropython.git .
        git checkout master
    - name: Initialize lv_bindings submodule
      run: git submodule update --init --recursive lib/lv_bindings
    - name: Update Unix port submodules
      run: make -C ports/unix VARIANT=dev DEBUG=1 submodules
    - name: Checkout LVGL submodule
      working-directory: ./lib/lv_bindings/lvgl
      run: |
        git fetch --force ${{ github.event.repository.git_url }} "+refs/heads/*:refs/remotes/origin/*"
        git fetch --force ${{ github.event.repository.git_url }} "+refs/pull/*:refs/remotes/origin/pr/*"
        git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
        git submodule update --init --recursive
    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross
    - name: Build the unix port
      run: make -j $(nproc) -C ports/unix VARIANT=dev DEBUG=1
    - name: Run tests      
      run: |
        export XDG_RUNTIME_DIR=/tmp
        lib/lv_bindings/tests/run.sh
    - name: Build ESP32 port
      run: |
        source tools/ci.sh && ci_esp32_idf43_setup
        source tools/ci.sh && ci_esp32_build
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - name: Build STM32 port
      run: |
          make -j $(nproc) -C ports/stm32 BOARD=STM32F7DISC
