name: SO3-LVGL Performance check
on: [push, pull_request, workflow_dispatch]
jobs:
  so3_lvgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install required APT packages
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: cmake gcc-arm-none-eabi  device-tree-compileru-boot-tools pkg-config bridge-utils qemu-system-arm
      
      - name: Remove useless dependency
        run: |
          sudo apt-get remove -y libyaml-dev
          
      - name: SO3-LVGL building components
        run: |
          wget https://github.com/smartobjectoriented/so3/archive/refs/heads/master.zip
          unzip master.zip
          mv so3-master so3
          cd so3
          patch -s -p0 < ci/so3_ci.patch
          cd u-boot; make vexpress_defconfig; make -j8; cd ..
          cd so3; make vexpress_fb_defconfig; make -j8; cd ..
          cd usr; ./build.sh; cd ..
          cd filesystem
          ./create_img.sh vexpress
          cd ../rootfs
          ./create_ramfs.sh vexpress
          cd ..
          ./deploy.sh -bu
          
      - name: SO3-LVGL performance check
        run: |
          cd so3
          ./st
          
      - name: Download_artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_performance
          path: so3/perf_check*.log

